apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: python-cnbpfovd
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap-test-organization-jk/python-cnbpfovd:jenkins-51e1306d53b88f6c28c85defae3fca51cba7bde3
        name: container-image  
